### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Compufreak345** [gordon-matt/OData_Test#2]
Hi,

I am currently working on a generic OData-WebApi myself and I would like to use your code as an inspiration. It would greatly help if you add a license so I know what I could do with your code and what I don't.

Thanks & best regards,
Christoph

**Comment by gordon-matt** [comment]
I appreciate that you had the courtesy of asking. This code is actually part of a much larger project of mine - a CMS which I plan to make open source. It's a project I've worked on over the last few years for MVC5 for my customers (I am a freelancer) and I am now upgrading it to .NET Core... I have it as a private GitHub repository right now and aim to make it public within the next few months or so. I'll probably release it all under MIT or similar. For now, I say use it as you wish. I only ask that you put my name (Matt Gordon) and a link to my GitHub page somewhere - perhaps as a comment in the code files or wherever.. and yeah; I hope it's useful to you. Enjoy.

**Comment by Compufreak345** [comment]
Thanks for clearing it up, I'll definitely put the remarks in the code and I am looking forward to have a look at your CMS. Continue your great work ;)

**Comment by gordon-matt** [comment]
@Compufreak345 Thanks. Also, if you want to be notified when I release the CMS, I suggest following me instead of starring this particular project.

**Comment by gordon-matt** [comment]
@Compufreak345 FYI - I have just released a new project : [Extenso Code Library](https://github.com/gordon-matt/Extenso). It contains the `GenericODataController` and the `IRepository<TEntity>` stuff, among other things. Feel free to contribute if you like as well. Enjoy!

**Comment by Compufreak345** [comment]
This is great news! 

We are currently using our own implementation based on your code (including your remarks) and have some deadlines to hold - as soon as we get some time we will have a close look at your new library and check if we can contribute something back to it. 

Thanks for sharing your code, it really helped us getting awesome stuff done (we are currently migrating an complex application from using Sharepoint as a datasource to a database and light at the end of the tunnel is becoming visible 😀 ).
